#!/bin/bash
cd /home/z/my-project/kivora
export NEXT_PUBLIC_SUPABASE_URL=https://asfzdbpfakwpiawhhrby.supabase.co
export NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzZnpkYnBmYWt3cGlhd2hocmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MDQwMzMsImV4cCI6MjA1ODA4MDAzM30.fake
./node_modules/.bin/next build 2>&1
